version: '2'
services:
  nginx:
    restart: always
    image: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./._start:/usr/share/nginx/html:ro
    ports:
      - "8099:80"
    extra_hosts:
     - "sandbox.icheck.com.vn:10.5.11.43"